### ISSUE TITLE
Add help to Indicators Form

### ISSUE THREAD

**Issue by kapsali29** [anthivaios/circular_economy_framework#6]
In the page where indicators data are submitted there are some *i* icons. When hovering over these icons a pop up message should be there indicating the indicators range. More specifically use the range types you have in your README.

```
recycled material: (>= 40) ->2 | (>=30) -> 1 | 0
disassemble time: (<= 7) ->2 | (<=16) -> 1 | 0
energy: (<= 2) ->2 | (<=2.4) -> 1 | 0
Co^2: (<= 0.5) ->2 | (<= 0.7) -> 1 | 0
Water: (<= 130) ->2 | (<= 145) -> 1 | 0
Checks: (>= 90) ->2 | (>= 60) -> 1 | 0
Remanufactured: (>= 15) ->2 | (>= 9) -> 1 | 0
Reused + Recycling: (>= 85) ->2 | (>= 70) -> 1 | 0
Eol: (>= 90) ->2 | (>= 75) -> 1 | 0
Secondary: (>= 40) ->2 | (>= 30) -> 1 | 0

```

**Comment by anthivaios** [comment]
Εχω προσθέσεi on hover να δείχνει κάποιες πληροφορίες το range καθώς και το Score ανάλογα το Input.
Tι πρέπει να προσθέσω?

**Comment by kapsali29** [comment]
Στο δικό μου όταν πάω να το τεσταρω δεν εμφανίζεται

Αποκτήστε το Outlook για Android<https://aka.ms/ghei36>

________________________________

**Comment by anthivaios** [comment]
Και στο mozilla και στο chrome που το δοκίμασα μου το κάνει (hover πάντα δεν ειναι clickable).

**Comment by kapsali29** [comment]
Το ξέρω ότι δεν είναι clickable σε μένα δεν κάνει hover από εκεί και έπειτα στείλε μια print screen.

Αποκτήστε το Outlook για Android<https://aka.ms/ghei36>

________________________________

**Comment by anthivaios** [comment]
![image](https://user-images.githubusercontent.com/44756424/95492775-431a0f80-09a4-11eb-961f-dc8a2ed0c01e.png)

**Comment by kapsali29** [comment]
Οκει μια χαρά συνέχισε με τα άλλα εμένα δεν συνεχίζει να το δείχνει πάντως

Αποκτήστε το Outlook για Android<https://aka.ms/ghei36>

________________________________

**Comment by anthivaios** [comment]
Οκ, θα δω τώρα το table γιατί έχω ένα θέμα με το width και θα ψάξω μετά τι μπορεί να φταιει. Και θα αρχίσω να γράφω το κομμάτι για τα εργαλεία και της χρήσης της εφαρμογής.

**Comment by kapsali29** [comment]
Για να δούμε μακάρι να προλάβετε

Αποκτήστε το Outlook για Android<https://aka.ms/ghei36>

________________________________
